### ISSUE TITLE
Sources de dechets-num

### ISSUE THREAD

**Issue by vallettea** [multibao/contributions#1]
hello,

je voudrais corriger deux trois trucs sur [cette page](http://www.dechets-num.net/contributions/scopyleft/dechets-num-contribution/Internet-des-objets) mais je trouve pas les source contrairement à ce qui était écrit dans le mail de Laurent Vitry.

**Comment by pointbar** [comment]
Oops, pas vu passer l'issue.

> https://github.com/scopyleft/dechets-num-contribution/blob/master/contributions/Internet-des-objets.md

**Comment by WolffThomas** [comment]
Salut Stef,

je ne vois pas de  dépôt "dechet-num-contributions" > fiche 
internet-des-objets sur multiBàO.

**Comment by pointbar** [comment]
Hi Thomas,

Le dépôt des déchets n’est pas exposésur multibao.

Il n’a pas trop ça place, je pense.

Comment va ? On se fait un point, dans la journée ?

See ya

Stéphane
