### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by orschiro** [multibao/contributions#3]
Dear all, 

I am very interested in your software which render markdown files in such a beautiful way!

Unfortunately I am not very proficient in French. Is there any English documentation that I can read?

Thankfully,

Robert

**Comment by WolffThomas** [comment]
Hi Robert, 

i can propose u a skype-demo. I'm available next week or in april. 
English documentation is not written (yet), still you can use the opensource for english documentation.

See you soon, 

Thomas 
thomas.wolff@cpcoop.fr
0033642459781

**Comment by orschiro** [comment]
Dear @WolffThomas,

Thank you for your proposition!

At the moment I am no longer interest in using Multibao.

However, I am very appreciative that you offered me a Skype demo.

Thankfully,

~Robert
